Update class.ecranvillage-shortcodes.php
RavanH/ecranvillage-api pull request #6
Opened 2024-09-03 23:23 UTC by rodinux

Try add audio_description if exist ??

I am not sure to understand all about the tables and conditions...

2024-09-03 23:24 UTC, rodinux commented
We can try do as possible... perhaps if audio_description is present it can be vue in same block as info ??

2024-09-19 01:42 UTC, RavanH requested changes
Est-ce que l'abréviation DA est possible? Il n'y a pas assez de place sur le site pour une colonne de plus avec entête si longue...

2024-09-19 01:42 UTC, RavanH commented on inc/class.ecranvillage-shortcodes.php
> +					. '<tr><th>Date</th><th>Heure</th><th>Version</th><th>Audio-Description</th><th>Info</th></tr></thead><tbody>';
plutôt "Audiodescription" ? https://fr.wikipedia.org/wiki/Audiodescription

2024-09-19 01:42 UTC, RavanH commented on inc/class.ecranvillage-shortcodes.php
> +					. '<tr><th>Date</th><th>Heure</th><th>Version</th><th>Audio-Description</th><th>Info</th></tr></thead><tbody>';
Ou peut-être abrévié à AD sinon la table devient trop large...

2024-09-19 01:42 UTC, RavanH commented on inc/class.ecranvillage-shortcodes.php
> +						. '<td itemprop="videoFormat">' . $version . '</td>' .'<td><meta itemprop="name" content="' . $audio_description . '">' . '<td class="extra">' . $info
`'<td>' . $audio_description  . '</td>'`

2024-09-19 01:42 UTC, RavanH commented on inc/class.ecranvillage-shortcodes.php
> +						. '<td itemprop="videoFormat">' . $version . '</td>' .'<td><meta itemprop="name" content="' . $audio_description . '">' . '<td class="extra">' . $info
( sans tag meta et fermeture du tag td )

2024-09-19 02:21 UTC, RavanH commented
> We can try do as possible... perhaps if audio_description is present it can be vue in same block as info ??

This might be a better idea than a dedicated column.

How is the audio_description property in the JSON represented if it exists? As a bool value (like `annulee`) or text? And ST-SME ?

2024-09-19 10:30 UTC, RavanH commented
Par exemple, le JSON du film Alien (avec AD/ST-SME dans l'appli) est bien https://programme.ecranvillage.net/films/1818.json ou pas? Pourtant, je n'y vois pas de champ audio_description ...

2024-09-19 10:47 UTC, rodinux commented
Ah oui, il faut bien qu j'ajoute dans le films/show.json, je viens de le faire !

2024-09-19 13:04 UTC, RavanH approved these changes

2024-09-19 13:04 UTC, merged